# Generated by Django 3.0.5 on 2020-05-16 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOrd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stulevel', models.CharField(default=0, max_length=20)),
                ('coursetitle', models.CharField(default=0, max_length=20)),
                ('tbname', models.CharField(default=0, max_length=20)),
                ('tbversion', models.CharField(default=0, max_length=20)),
                ('tbpublish', models.CharField(default=0, max_length=20)),
                ('tbauthor', models.CharField(default=0, max_length=20)),
                ('tbisbn', models.CharField(default=0, max_length=20)),
                ('tbpurpose', models.CharField(default=0, max_length=20)),
                ('tbfteach', models.CharField(default=True, max_length=10)),
                ('teachingtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.TeachingTask', verbose_name='教学计划')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MyUser', verbose_name='用户')),
            ],
        ),
    ]
