# Generated by Django 3.0.5 on 2020-05-16 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseunit', models.CharField(max_length=50, verbose_name='开课单位')),
                ('courseid', models.IntegerField(default=0, verbose_name='课程编号')),
                ('coursename', models.CharField(max_length=50, verbose_name='课程名称')),
                ('xueshi', models.IntegerField(default=0, verbose_name='总学时')),
                ('teaching', models.IntegerField(default=0, verbose_name='理论')),
                ('practice', models.IntegerField(default=0, verbose_name='实践')),
                ('xuefen', models.FloatField(default=0, verbose_name='学分')),
                ('grade', models.IntegerField(default=0, verbose_name='年级')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('studentnum', models.IntegerField(default=0, verbose_name='人数')),
                ('xiaoqu', models.CharField(max_length=50, verbose_name='校区')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MyUser', verbose_name='单位')),
            ],
            options={
                'verbose_name': '教学计划',
                'verbose_name_plural': '教学计划',
            },
        ),
    ]
